### ISSUE TITLE
ugh i'm totally going to be *that* guy filing the first issue

### ISSUE THREAD

**Issue by imjared** [airbnb/hypernova#1]
looks like the nodejs link is broken :(
https://github.com/airbnb/hypernova/blob/master/docs/clients.md

**Comment by goatslacker** [comment]
Thanks for being that person :)

We'll be pushing up the code pretty soon. Apologies for the delay.

**Comment by ljharb** [comment]
https://www.npmjs.com/package/hypernova-client and https://github.com/airbnb/hypernova-node are now available.
