### ISSUE TITLE
createApplication in docs but not released

### ISSUE THREAD

**Issue by jburghardt** [airbnb/hypernova#140]
The createApplication feature has been merged with https://github.com/airbnb/hypernova/pull/132 and is currently in the docs but has not been released yet. This is quite confusing as i was not sure why it was not working.

A new version to release this feature would be great !

**Comment by ljharb** [comment]
It's common and expected that the master branch of a repo may contain unreleased code. If you check https://github.com/airbnb/hypernova/releases and click through to the [version](https://github.com/airbnb/hypernova/tree/v2.3.0) you're interested in, you'll see what it has available.

I'll try to get a release out soonish.

**Comment by jburghardt** [comment]
Oh i know its common. I guess i was just trying to get this on the radar as we are looking to use some middlewares with hypernova. 

Can be closed then and thanks

**Comment by agis** [comment]
Getting this in a release would be great, we're also interested in this feature. Thanks!
