### ISSUE TITLE
Ruby version in example is ambiguous

### ISSUE THREAD

**Issue by alexsbryan** [airbnb/hypernova#150]
Appreciate the work on the project! I had ruby 2.5.x running on my system and couldn't get the example to run on account of what seemed like this issue: https://github.com/rails/rails/issues/27670 (`Fixnum is deprecated` error). After installing 2.3.8 it worked well enough to test, but there were some odd errors in the server logs. 

I'd like to request that the ruby version be specified in the Gemfile for anyone who might run into this in the future.

**Comment by ljharb** [comment]
Sure, a PR to add that would be great.

**Comment by marconi1992** [comment]
@ljharb I think this issue is solved by the merged PR above.

**Comment by ljharb** [comment]
Closed in #151.
