### ISSUE TITLE
This project is no longer maintain?

### ISSUE THREAD

**Issue by leandromatos** [airbnb/hypernova#175]
I seen a lot of pull request and issues opened a long time ago. This project is no longer maintain?

Is harded to choose a project like Hypernova for using when his not receive update a long time ago.

**Comment by ljharb** [comment]
It's still maintained.

**Comment by marcus-sa** [comment]
@ljharb doesn't seem like it.

**Comment by ljharb** [comment]
@marcus-sa things seem like lots of things, not sure what to tell you.

**Comment by eliecer2323** [comment]
I'm also looking into the whole Ara Framework solution, but it seems like most of the libraries haven't been updated since three years ago, it makes me doubt the support I can have if I choose it for my project
