### ISSUE TITLE
Broken example

### ISSUE THREAD

**Issue by alexindigo** [airbnb/hypernova#19]
In your readme, example component returns object: `{default: [Function]}`,
but in your BatchManager it expects a function:

https://github.com/airbnb/hypernova/blob/master/src/utils/BatchManager.js#L141

Did I miss something or there is more to it than you have in the example/readme.

Thank you.

**Comment by goatslacker** [comment]
I'll change it to regular CJS to simplify it.

The original reasoning is that you'll most likely be doing some transpiling for the browser and probably for the server too since some features don't run on latest node. If you're transpiling then you'll probably be either using `import` on the server, or you'll figure out how to transpile `export default` into `module.exports` with some plugin, maybe [this one](https://github.com/59naga/babel-plugin-add-module-exports)?

These are too many assumptions though. :) Thanks for bringing it up.

**Comment by alexindigo** [comment]
Yep, I did transpile with babel and react + es2015 presents, this what I've got:

```
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _react = require('react');

var _react2 = _interopRequireDefault(_react);

var _hypernovaReact = require('hypernova-react');

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function MyComponent(props) {
  return _react2.default.createElement(
    'div',
    null,
    'Hello, ',
    this.props.name,
    '!'
  );
}

exports.default = (0, _hypernovaReact.renderReact)('MyComponent.js', MyComponent);
```

And server side rendering is all I care about and I'd be getting my components in es6/jsx so compiling will be part of the deploy process.

**Comment by alexindigo** [comment]
One more question, about that example:

```
function MyComponent(props) {
  return <div>Hello, {this.props.name}!</div>;
}
```

You're passing `props` object, but using `this.props`. :)

**Comment by alexindigo** [comment]
Will check your example, thanks.

**Comment by goatslacker** [comment]
@alexindigo where is that at? That's a bug.

**Comment by alexindigo** [comment]
I see you fixed it here, but old version is still on npm:

![this.prop.name](http://ia.gs/gWUK/Image%202016-06-22%20at%204.04.40%20PM.png)

**Comment by alexindigo** [comment]
Playing more and with your updated example, I noticed that `onClick` handler gets lost.

component:

```
import React from 'react';
import { renderReact } from 'hypernova-react';

function MyComponent(props) {
  return <div onClick={() => alert('Click handlers work.')}>Hello, {props.name}!</div>;
}

export default renderReact('MyComponent.js', MyComponent);
```

Compiled:

```
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _react = require('react');

var _react2 = _interopRequireDefault(_react);

var _hypernovaReact = require('hypernova-react');

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function MyComponent(props) {
  return _react2.default.createElement(
    'div',
    { onClick: function onClick() {
        return alert('Click handlers work.');
      } },
    'Hello, ',
    props.name,
    '!'
  );
}

exports.default = (0, _hypernovaReact.renderReact)('MyComponent.js', MyComponent);
```

Output:

```
{
  "success": true,
  "error": null,
  "results": {
    "MyComponent.js": {
      "name": "MyComponent.js",
      "html": "<div data-hypernova-key=\"MyComponentjs\"><div data-reactroot=\"\" data-reactid=\"1\" data-react-checksum=\"1633367769\"><!-- react-text: 2 -->Hello, <!-- /react-text --><!-- react-text: 3 -->Alex<!-- /react-text --><!-- react-text: 4 -->!<!-- /react-text --></div></div>\n<script type=\"application/json\" data-hypernova-key=\"MyComponentjs\"><!--{\"theseAreProps\":true,\"name\":\"Alex\",\"someOtherProps\":[\"one\",\"two\",\"three\"]}--></script>",
      "meta": {},
      "duration": 9.820868,
      "statusCode": 200,
      "success": true,
      "error": null
    }
  }
}
```

`onClick` is gone, not sure if it's a feature or a bug.

**Comment by alexindigo** [comment]
And one more thing, it's not clear to me (yet),
why I need to have `import { renderReact } from 'hypernova-react';`
as part of the component, is it different from the built-in React method?

Thank you.

**Comment by alexindigo** [comment]
I see, it doesn't really renders it, more like priming for the hypernova usage:

```
function (props) {
          var contents = _server2['default'].renderToString(_react2['default'].createElement(component, props));
          return (0, _hypernova.serialize)(name, contents, props);
        }
```

**Comment by goatslacker** [comment]
@alexindigo ah yes, npm has the old README. When I publish a next version to npm the README will be updated there as well.

As for `onClick` handler being "lost", React doesn't include any event handlers in the markup itself, that all lives in the code which is also included on the page and runs on the page.

The markup that you're producing is just the server-rendered HTML that is displayed to the user. Once you're on the browser with the JS loaded the React component will become "active" which will enable any event handlers and run `componentDidMount` on your components.
