### ISSUE TITLE
The ENCODE array is changed in-place every time

### ISSUE THREAD

**Issue by fatfisz** [airbnb/hypernova#30]
```js
function decode(res) {
  const jsonPayload = ENCODE.reverse().reduce((str, coding) => {
    ...
}
```

`Array.prototype.reverse` changes the array in place, is this desirable in this case? The second time `load` is called (and `decode` too as a result), `ENCODE.reverse()` should have the same value as `ENCODE` in the beginning, i.e.

```js
> ENCODE = ['a', 'b']
["a", "b"]
> ENCODE.reverse()
["b", "a"]
> ENCODE.reverse()
["a", "b"]
```

**Comment by ljharb** [comment]
As long as we can come up with a failing test for this, we should probably just be using `reduceRight` instead.

**Comment by fatfisz** [comment]
Big thanks for the fix!

**Comment by ljharb** [comment]
Thanks for the report!
