### ISSUE TITLE
Promise Error on Basic Use Case

### ISSUE THREAD

**Issue by chibicode** [airbnb/hypernova#43]
Hi, I attempted to test `hypernova` without loading a component from a file like this (it handles JSX because I'm compiling server JS file w/ webpack):

```js
import hypernova from 'hypernova/server'
import { renderReact } from 'hypernova-react'

const TestComponent = () => <div>Hello Hypernova</div>

hypernova({
  devMode: true,
  getComponent: function () {
    return renderReact('TestComponent', TestComponent)
  }
})
```

Then when I use this from Rails:

```ruby
# view
# <%= render_react_component "Test" %>

# controller
around_action :hypernova_render_support

# initializer
if Rails.env.development?
  require "hypernova/plugins/development_mode_plugin"
  Hypernova.add_plugin!(DevelopmentModePlugin.new)
end

Hypernova.configure do |config|
  config.host = "localhost"
  config.port = 8080
end
```

I do see hypernova's `div` rendered, but the content is empty:

```html
<div data-hypernova-key="Test" data-hypernova-id="59829cc1-7a43-4c1a-a63e-e59458fb4459"></div>
```

On the server, I get this error:

```
Warning: a promise was created in a handler but was not returned from it, see http://goo.gl/rRqMUw
```

I'm not sure how to go about debugging this. Any help would be much appreciated.

**Comment by ljharb** [comment]
The string you pass to `renderReact` must match your hypernova key and the string you pass into `render_react_component` - you're passing `TestComponent` instead of `Test`.

**Comment by chibicode** [comment]
@ljharb sorry - I didn't realize that those had to match. Here's why I got confused:

![image](https://cloud.githubusercontent.com/assets/992008/22227184/77765724-e20d-11e6-97e4-bc67610c47b1.png)
