### ISSUE TITLE
security issue?

### ISSUE THREAD

**Issue by dfguo** [airbnb/hypernova#49]
I was looking through code and found that it's vulnerable to attacks when source code uses native node modules, such as fs.

```
const fs = require('fs');
const testFolder = './';

fs.readdir(testFolder, (err, files) => {
    files.forEach(file => {
          console.log(file);
            });
})
```

These native modules are still executed in ```runInContext``` of createVM.js.

**Comment by ljharb** [comment]
What's the attack you have in mind?

**Comment by ljharb** [comment]
(Keeping in mind that this is your own code running on your own server)

**Comment by goatslacker** [comment]
Hypernova's default configuration is sort of like eval in the sense that you shouldn't run untrusted code on it. If you want a more sandbox like environment for security reasons you can provide your own implementation of `require` and blacklist native modules such as `fs`.

**Comment by dfguo** [comment]
I raised this issue because I see no reason why we should allow web FE written code to be able to run ```require```. I will look into @goatslacker 's suggestion.
