### ISSUE TITLE
getComponent support function return a Promise

### ISSUE THREAD

**Issue by baoti** [airbnb/hypernova#51]
I am working on vue bindings for Hypernova, but [vue-server-renderer](https://www.npmjs.com/package/vue-server-renderer) renderer pass html by callback:
```
const Vue = require('vue')
 
const renderer = require('vue-server-renderer').createRenderer()
 
const vm = new Vue({
  render (h) {
    return h('div', 'hello')
  }
})

renderer.renderToString(vm, (err, html) => {
  console.log(html) // -> <div server-rendered="true">hello</div> 
})
```

So, I'd like `getComponent` support a function which return a Promise, just like `props => Promise.resole(html)`.

**Comment by baoti** [comment]
Vue bindings for server like this:
```
export const renderVue = (name, component) => hypernova({
  server() {
    return (props) => {
      const vm = new component({ propsData: props });
      return new Promise((resolve, reject) => {
        renderer.renderToString(vm, (err, html) => {
          if (err) {
            reject(err);
          } else {
            resolve(serialize(name, html, props));
          }
        });
      });
    };
  },
}
```

**Comment by ljharb** [comment]
I'm not sure I understand - are you saying that the vue server renderer does not synchronously produce a string?

**Comment by baoti** [comment]
@ljharb Yes.

**Comment by ljharb** [comment]
According to [the code](https://github.com/airbnb/hypernova/blob/5dbddc4dba65bd9ee2bcbc04fec11713bfa89d57/src/utils/BatchManager.js#L145-L147), `getComponent`'s return value is already passed into `Promise.resolve`.

**Comment by baoti** [comment]
`getComponent`'s return value is a function, but `renderFn(context.props)`'s return value is a Promise.

**Comment by baoti** [comment]
[```context.html = renderFn(context.props);```](https://github.com/airbnb/hypernova/blob/5dbddc4dba65bd9ee2bcbc04fec11713bfa89d57/src/utils/BatchManager.js#L160)

`context.html` got a Promise, not a string.

**Comment by ljharb** [comment]
Gotcha; so you'd need https://github.com/airbnb/hypernova/blob/5dbddc4dba65bd9ee2bcbc04fec11713bfa89d57/src/utils/BatchManager.js#L160 changed.

Seems doable/reasonable to me.

**Comment by marconi1992** [comment]
@baoti you could use this npm package https://www.npmjs.com/package/hypernova-vue, there's an article about it too https://medium.com/@felipegaiacharly/using-vue-js-with-hypernova-server-ce792dcf1ac7

**Comment by baoti** [comment]
https://github.com/airbnb/hypernova/commit/ca74d2123708f29ab3bb3cc897874e2d894b8394#diff-19b62c5258de09e32f97ee52dd8e9615

**Comment by baoti** [comment]
It's already supported since [2.1.1] - 2017-06-15, [commit](https://github.com/airbnb/hypernova/commit/ca74d2123708f29ab3bb3cc897874e2d894b8394#diff-19b62c5258de09e32f97ee52dd8e9615).

**Comment by baoti** [comment]
@marconi1992 Thanks, It works.
