### ISSUE TITLE
Clarification in README

### ISSUE THREAD

**Issue by magicmark** [airbnb/hypernova#58]
Hi all! Thanks for this awesome project!

From the README:
```
  // the port the app will start on
  port: 8080,
  // whether or not to run in parallel using all available cpus
  endpoint: '/batch'
  // default endpoint path
}
```

What config option is "whether or not to run in parallel using all available cpus" referring to? It also looks like the 'default endpoint path' should be on that line instead.

Thanks!

**Comment by ljharb** [comment]
Indeed, that looks like a merge conflict gone bad. That text is referring to a now-removed option and should be removed. Mind opening a PR to fix it?
