### ISSUE TITLE
I'd like to be able to add my own log transports

### ISSUE THREAD

**Issue by morganpackard** [airbnb/hypernova#64]
I see that I have the ability to add a `logger` property to the config object passed in to the hypernova initializer. However, it looks like this only gives me the ability to override these defaults:

```
{
  level: 'info',
  colorize: true,
  timestamp: true,
  prettyPrint: process.env.NODE_ENV !== 'production',
}
```
What I'd really like to be able to do is pass in my own transports to Winston so I can hook in to my remote logging service. Any plans to add this feature?

**Comment by goatslacker** [comment]
We can probably add a transports key to the config object. PR's welcome.

**Comment by morganpackard** [comment]
Thanks!

**Comment by damianleung** [comment]
@goatslacker so, did this happen already? I can't get any logging from my setup.

**Comment by wingleung** [comment]
gave a try, feedback is welcome -> airbnb/hypernova#117

**Comment by wingleung** [comment]
just saw a PR from a couple of months ago -> https://github.com/airbnb/hypernova/pull/104
so my PR might be obsolete https://github.com/airbnb/hypernova/pull/117

**Comment by schleyfox** [comment]
Fixed in https://www.npmjs.com/package/hypernova/v/2.2.6 .  Thanks everyone!
