### ISSUE TITLE
Hypernova with Rails API

### ISSUE THREAD

**Issue by arefaslani** [airbnb/hypernova#85]
Having a Rails API as backend, can I use Hypernova to render json data retrieved from the API and use that data for server side rendering? Is there any example showing how to use Rails API with Hypernova?

**Comment by ljharb** [comment]
When you say "Rails API", do you also mean Rails is your webserver?

**Comment by arefaslani** [comment]
@ljharb I use Nginx + Unicorn combination

**Comment by goatslacker** [comment]
There's a simple Rails example which can be [found here](https://github.com/airbnb/hypernova/tree/master/examples/simple). Is that what you're looking for?

**Comment by arefaslani** [comment]
@goatslacker No. I have a Rails JSON API (api.chanka.ir) as back-end and a React application for front-end. Is it possible to use Hypernova for server-side rendering in this type of applications?

**Comment by ljharb** [comment]
You'd need an actual web server - the thing serving your frontend - to hook into hypernova. The API should be mostly irrelevant.
